### ISSUE TITLE
Problem with netcdf when compiling Trilinos

### ISSUE THREAD

**Issue by unfelipe** [trilinos/trilinos.github.io#28] opened 2020-02-14 05:36 UTC
Hello, 

     I am trying to install Trilinos 12.17 in my local cluster.

     After successfully generating with cmake, I proceed on compiling, but I get errors like these:

     ex_put_variable_param.c:(.text+0x2e8): undefined reference to `nc_def_dim'
     ex_utils.c:(.text+0x2fad): undefined reference to `nc_put_att_float'

   Investigating, I learned that they are due to bad linking or referencing to NetCDF. But, I do have NetDCF installed,  netcdf-c-4.7.3. 
  When building Trilinos, I do:

 -DTPL_Netcdf_LIBRARIES='/home/Felipe/BIGSOFTWARE/netcdf-c-4.7.3'
 -DNetcdf_INCLUDE_DIRS='/home/Felipe/BIGSOFTWARE/netcdf-c-4.7.3/include'

 and all good, it builds. The error comes with the compiling, when doing the 'make install'
 I am doing; make -j8 && ctest -j8 && make -j8 install 

 What should I do?
 Should I run a test on my netcdf?
 Should I check for linking from Trilinos directory? is there any other better way to link? maybe the 'library dirs' needs to be more specific, but inside netcdf folder there are many subfolders whose name start with lib.. (such as libsrc, libserp, liblib, libdap..)
     
I would appreciate your help, as I do not know what to do.
Felipe

**Comment by gsjaardema** [comment] 2020-02-14 13:52
Can you try adding '/lib' to the end of your `-DTPL_Netcdf_LIBRARIES` define:
```
-DTPL_Netcdf_LIBRARIES='/home/Felipe/BIGSOFTWARE/netcdf-c-4.7.3/lib'
```

**Comment by mhoemmen** [comment] 2020-02-14 16:23
@unfelipe Unfortunately, Trilinos' web page points users here instead of to github.com/trilinos/Trilinos for posting issues.  New Trilinos issues should be posted at github.com/trilinos/Trilinos/issues.

**Comment by unfelipe** [comment] 2020-02-15 07:33
Hello, Greg Sjaardema,

   Thanks for replying.

    I tried adding netcdf../lib, but it did not work. The message was
related to the fact that the folder lib does not exist.

    What exists are several folders whose names start with lib, for example
liblib, libsrc, libdap2, 4..

    Then I tried with /libsrc. which seemed promising, but it did not work
either.

     The generating goes well.. somehow it does not care about this
linking.. This is surprising. It does not report any warning or flag about
the linking weakness/error.
        -- Generating done
        -- Build files have been written to:
/home/Felipe/BIGSOFTWARE/Trilinos-master/MYBU

     then, when doing make install, the error comes:
ex_put_nodal_var_int.c:(.text+0x92): undefined reference to
`nc_put_vara_double'
ex_put_nodal_var_int.c:(.text+0xf1): undefined reference to
`nc_put_vara_float'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/seacas/applications/epu/epu] Error 1
make[1]: *** [packages/seacas/applications/epu/CMakeFiles/epu.dir/all]
Error 2
make: *** [all] Error 2

what do you think is missing?

cheers many,
Felipe

**Comment by gsjaardema** [comment] 2020-02-16 04:25
OK.  I think the problem is that you only have the netcdf source code.  You need to build and install the NetCDF library before it can be used with Trilinos.  You will probably also need to get a copy of the HDF5 library since that is an optional dependency of NetCDF.

If you are building a parallel (MPI) version of Trilinos, then you should also build a parallel HDF5 and then a parallel NetCDF.  Once those are built, then you can build Trilinos.

**Comment by maherou** [comment] 2020-05-11 14:09
Closing as out of scope.

**Closed by maherou** 2020-05-11 14:09 UTC
